use_frameworks!

platform :ios, '10.0'

target 'NewChatDemo0_Example' do
  pod 'NewChatDemo0', :path => '../'
  pod 'ImageLoader'
  pod "BSImagePicker"
  pod 'SwiftEventBus', :tag => '5.1.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'

  target 'NewChatDemo0_Tests' do
    inherit! :search_paths

    
  end
end
